app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: asdline
    pool-size: 30

#  docker run --name springpostgres -e POSTGRES_PASSWORD=asdline -d -p 0.0.0.0:5432:5432 postgres:alpine